
export const caseStudies = [
  {
    title: "Citizen Portal for Ministry of Chittagong Hill Tracts Affairs",
    slug: "citizen-portal",
    description: "Designed a comprehensive Integrated Digital Service Delivery Platform to modernize government services through web and mobile applications, centralizing all services within a unified digital ecosystem.",
    image: "/images/IDSDP_Mock.jpg",
    hint: "government citizen portal",
    metrics: [
      { name: 'Processing Time', 'Reduction': 40 },
      { name: 'User Satisfaction', 'Increase': 60 },
      { name: 'Adoption Rate', 'Increase': 75 },
    ],
    chartType: 'bar',
    prototypeLink: "https://www.figma.com/proto/pJSlC3TuvjntdmCl1P8Odw?node-id=1110-416",
  },
  {
    title: "Queue Management System SaaS",
    slug: "queue-management-system",
    description: "A cloud-based SaaS platform designed to streamline customer flow and reduce wait times for businesses across various industries, from healthcare to retail.",
    image: "/images/queue-management-feature.png",
    hint: "queue management",
    metrics: [
      { month: 'Jan', waitTime: 60 },
      { month: 'Feb', waitTime: 55 },
      { month: 'Mar', waitTime: 50 },
      { month: 'Apr', waitTime: 45 },
      { month: 'May', waitTime: 40 },
      { month: 'Jun', waitTime: 35 },
    ],
    chartType: 'line',
    prototypeLink: "https://queue.meghcreations.com/",
  },
  {
    title: "Complaint, Case and Court Management System",
    slug: "court-management-system",
    description: "A comprehensive system to digitize and streamline court proceedings, from case filing and scheduling, to verdict delivery and records management.",
    image: "/images/case.png",
    hint: "court management system",
    metrics: [
        { name: 'Case Processing', value: 50 },
        { name: 'Filing Errors', value: 70 },
        { name: 'Doc Retrieval', value: 80 },
    ],
    chartType: 'bar',
    prototypeLink: "https://www.figma.com/design/ZRz0BHna22Z5QAwsKIQtAi?node-id=5-189",
  },
  {
    title: "Integrated Billing System SaaS",
    slug: "integrated-billing-system",
    description: "A multi-tenant SaaS platform to automate the entire billing lifecycle, from invoicing and subscriptions to payment processing and revenue recognition.",
    image: "/images/billing.jpg",
    hint: "saas billing",
    metrics: [
      { quarter: 'Q1', revenue: 2000 },
      { quarter: 'Q2', revenue: 2500 },
      { quarter: 'Q3', revenue: 3200 },
      { quarter: 'Q4', revenue: 4100 },
    ],
    chartType: 'area',
    prototypeLink: "https://www.figma.com/design/0vLT85Ubv0eRqZyLszhyIm?node-id=3-2",
  },
];
